# Configuração do caminho base para os repositórios Git clonados
branchlift.git.repos.base-path=/tmp/branchlift_repos

# Configuração do caminho base para os diretórios dos ambientes provisionados
branchlift.environments.base-path=/tmp/branchlift_environments

# Configuração do Spring Boot para o Banco de Dados (será sobrescrito pelo docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/branchlift_db
spring.datasource.username=branchlift_user
spring.datasource.password=*******
spring.jpa.hibernate.ddl-auto=update